/**
 * License Verification Module
 *
 * Embedded in the app to verify signed license files.
 * Uses the PUBLIC key (never the private key) to verify signatures.
 *
 * The public key is embedded here — this file gets obfuscated + compiled
 * into the .exe so it's hard to tamper with.
 */

const crypto = require('crypto');
const os = require('os');
const fs = require('fs');
const path = require('path');
const { execSync } = require('child_process');

// ── Embedded PUBLIC key (generated by license-tool/generate-keys.js) ──────────
// Replace this with your actual public.pem content after generating keys!
const PUBLIC_KEY = `-----BEGIN PUBLIC KEY-----
MIICIjANBgkqhkiG9w0BAQEFAAOCAg8AMIICCgKCAgEAycXxzWLdKBjgYc7l4YaN
nBYGEJ6CczluaQOKn3RBLhMfO1RDmmt4rxiMxg6k7twrvIhOLDSleRkgRrviJToP
B1zpwUHTQM1bVqOBpYMoysExR/RPxvIZ6Hl1Aptuqh/MIaavxQMjRdh6XdZ0G2Bp
Pza0k0mP9N5BaIMloJKeQN9vsOCX9HpowjBWykJolBOjddoWTJbOwPZV5NFBEX6x
Nw2uiPGydY1v6FZjMt4EIBbNfcjgi7QMtUI0D7xgX+gyKNbGaja8ontKkM+ROZW8
4Rt9IyNARsoBy3WC7qQ7nMM0r24tN3QT+rcZFjG/9ajg3arZL2RupAA462qhWZat
qFoecAv+9pBOlAdSOp24qpeOnAYLIbdA6eGg2HqDcof1OOZYTRBN9H2ikHKQf30t
Gp1qh1OZgPryRrczBPU/S452BxHSPzXXZ01Bl+Vx4FCBhNsSU7/5+631sG/BwPbF
LITQn4k41PS69dgsz9pMaFLobJNhZATb3x+ARpposmS08vir5lwcJLvnuaun+0NR
vWjS8M+KkpH/Q39MZ+xkc59itp2A9tq4VTwrp97FevQT+mMPJgX96I8v2P2bcP6l
EwiDLdWak8CTkQKZGdtZRnd8gaKnU2m7gayNWIQzkXib5aKGcBLmWhglkHT3dUwv
Vg3E9WtEtiIhLRxtDEdRmMcCAwEAAQ==
-----END PUBLIC KEY-----`;

// ── License file location ──────────────────────────────────────────────────────
// Look in the same directory as the executable, or a "data" subfolder, or app root
function getLicensePaths() {
  const possible = [];

  // When running via pkg: __dirname is inside the executable
  if (process.pkg) {
    possible.push(path.join(path.dirname(process.execPath), 'license.lic'));
    possible.push(path.join(path.dirname(process.execPath), 'data', 'license.lic'));
  }

  // When running from source (dev mode)
  possible.push(path.join(__dirname, '..', 'license.lic'));
  possible.push(path.join(__dirname, '..', 'data', 'license.lic'));
  possible.push(path.join(process.cwd(), 'license.lic'));

  return possible;
}

// ── Hardware fingerprint ───────────────────────────────────────────────────────
function getHardwareId() {
  const parts = [];

  // CPU info
  const cpus = os.cpus();
  if (cpus.length > 0) {
    parts.push(cpus[0].model.trim());
    parts.push(String(cpus.length));
  }

  // Total memory
  parts.push(String(os.totalmem()));

  // Hostname
  parts.push(os.hostname());

  // MAC addresses (sorted for consistency)
  const interfaces = os.networkInterfaces();
  const macs = [];
  for (const name of Object.keys(interfaces)) {
    for (const iface of interfaces[name]) {
      if (!iface.internal && iface.mac && iface.mac !== '00:00:00:00:00:00') {
        macs.push(iface.mac);
      }
    }
  }
  macs.sort();
  if (macs.length > 0) {
    parts.push(macs.join('|'));
  }

  // Windows-specific: motherboard UUID (very unique)
  try {
    const stdout = execSync('wmic csproduct get uuid', {
      timeout: 3000,
      encoding: 'utf8',
      stdio: ['pipe', 'pipe', 'pipe'],
    });
    const uuid = stdout.replace('UUID', '').trim();
    if (uuid && uuid.length > 10) {
      parts.push(uuid);
    }
  } catch {
    // WMIC might not be available, skip silently
  }

  // Hash everything into a consistent ID
  const hash = crypto.createHash('sha256').update(parts.join('|')).digest('hex');
  // First 32 chars for readability
  return hash.substring(0, 32);
}

// ── Anti-tamper: store last-checked time to detect clock rollback ──
function getAntiTamperPath() {
  if (process.pkg) {
    return path.join(path.dirname(process.execPath), 'data', '.license-check');
  }
  return path.join(__dirname, '..', 'data', '.license-check');
}

function checkClockManipulation() {
  try {
    const checkPath = getAntiTamperPath();
    const dir = path.dirname(checkPath);
    if (!fs.existsSync(dir)) {
      fs.mkdirSync(dir, { recursive: true });
    }

    const now = Math.floor(Date.now() / 1000);
    let lastCheck = 0;

    if (fs.existsSync(checkPath)) {
      lastCheck = parseInt(fs.readFileSync(checkPath, 'utf8').trim(), 10);
    }

    // Write current timestamp
    fs.writeFileSync(checkPath, String(now));

    // If last check was in the future relative to now, clock was rolled back
    if (lastCheck > now + 60) {
      // Allow 60 seconds of drift
      return { tampered: true, drifted: lastCheck - now };
    }

    return { tampered: false };
  } catch {
    // If we can't check, allow it (don't lock legitimate users due to permissions)
    return { tampered: false };
  }
}

// ── License verification ───────────────────────────────────────────────────────
function verifyLicense(licenseData, skipAntiTamper) {
  try {
    const { signature, ...payload } = licenseData;

    if (!signature) {
      return { valid: false, reason: 'Missing signature' };
    }

    // Verify the signature
    const verifier = crypto.createVerify('sha256');
    verifier.update(JSON.stringify(payload));
    verifier.end();

    const isValid = verifier.verify(PUBLIC_KEY, signature, 'base64');
    if (!isValid) {
      return { valid: false, reason: 'Invalid signature (tampered file)' };
    }

    // Check hardware match
    const localId = getHardwareId();
    if (payload.hardware_id !== localId) {
      return {
        valid: false,
        reason: `License locked to different machine`,
        localId,
        licenseId: payload.hardware_id,
      };
    }

    // Check clock manipulation (only during regular checks, not during activation)
    if (!skipAntiTamper) {
      const clockCheck = checkClockManipulation();
      if (clockCheck.tampered) {
        return {
          valid: false,
          reason: `System clock tampering detected (${Math.floor(clockCheck.drifted / 60)} min rollback). Please fix your date/time and restart.`,
        };
      }
    }

    // Check expiry
    const now = new Date();
    const expiry = new Date(payload.expires_at + 'T23:59:59');
    if (now > expiry) {
      return { valid: false, reason: `License expired on ${payload.expires_at}` };
    }

    return {
      valid: true,
      client_name: payload.client_name,
      expires_at: payload.expires_at,
      days_remaining: Math.ceil((expiry - now) / (1000 * 60 * 60 * 24)),
    };
  } catch (err) {
    return { valid: false, reason: `Verification error: ${err.message}` };
  }
}

// ── Load and verify license from disk ──────────────────────────────────────────
function checkLicenseFile() {
  const paths = getLicensePaths();

  for (const p of paths) {
    try {
      if (fs.existsSync(p)) {
        const raw = fs.readFileSync(p, 'utf8');
        const data = JSON.parse(raw);
        const result = verifyLicense(data);

        if (result.valid) {
          return { found: true, path: p, ...result };
        }

        return { found: true, path: p, ...result };
      }
    } catch {
      continue;
    }
  }

  return {
    found: false,
    valid: false,
    reason: 'No license file found',
    localId: getHardwareId(),
  };
}

module.exports = {
  getHardwareId,
  verifyLicense,
  checkLicenseFile,
  getLicensePaths,
};
